---
mdd_data:
  mdd:openconfig:
    openconfig-spanning-tree:stp:
      openconfig-spanning-tree:global:
        openconfig-spanning-tree:config: {}
      openconfig-spanning-tree:interfaces:
        openconfig-spanning-tree:interface: []
      openconfig-spanning-tree:rapid-pvst:
        openconfig-spanning-tree:vlan: []
      openconfig-spanning-tree-ext:pvst:
        openconfig-spanning-tree-ext:vlan: []
      openconfig-spanning-tree:mstp:
        openconfig-spanning-tree:config: {}
        openconfig-spanning-tree:mst-instances:
          openconfig-spanning-tree:mst-instance: []
mdd_tags:
- WAN_router
